apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | quote}}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  access_key: {{ randAlphaNum 12 | b64enc | quote }}
  secret_key: {{ randAlphaNum 12 | b64enc | quote }}
